[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/gorest"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gorest"
  status = 200